# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(587, 138)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(12)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.btnValidaCPF = QtWidgets.QPushButton(self.centralwidget)
        self.btnValidaCPF.setMinimumSize(QtCore.QSize(150, 0))
        self.btnValidaCPF.setObjectName("btnValidaCPF")
        self.gridLayout.addWidget(self.btnValidaCPF, 1, 2, 1, 2)
        self.btnGerarCPF = QtWidgets.QPushButton(self.centralwidget)
        self.btnGerarCPF.setObjectName("btnGerarCPF")
        self.gridLayout.addWidget(self.btnGerarCPF, 2, 2, 1, 2)
        self.inputValidacpf = QtWidgets.QLineEdit(self.centralwidget)
        self.inputValidacpf.setMinimumSize(QtCore.QSize(200, 0))
        self.inputValidacpf.setSizeIncrement(QtCore.QSize(0, 0))
        self.inputValidacpf.setObjectName("inputValidacpf")
        self.gridLayout.addWidget(self.inputValidacpf, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.labelRetorno = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(19)
        self.labelRetorno.setFont(font)
        self.labelRetorno.setText("")
        self.labelRetorno.setReadOnly(True)
        self.labelRetorno.setObjectName("labelRetorno")
        self.gridLayout.addWidget(self.labelRetorno, 3, 0, 1, 4)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Valida ou Gera CPF"))
        self.btnValidaCPF.setText(_translate("MainWindow", "Validar"))
        self.btnGerarCPF.setText(_translate("MainWindow", "Gerar"))
        self.label.setText(_translate("MainWindow", "Gera CPF"))
        self.label_2.setText(_translate("MainWindow", "Valida CPF:"))
